// Code generated by hertztool.

package handler

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"code.byted.org/analyzers/go_cleaner/app/cleaner/api/biz/model"
	"code.byted.org/analyzers/go_cleaner/app/cleaner/api/dal/codemeta"
	"code.byted.org/gopkg/logs"
	"code.byted.org/middleware/hertz/pkg/app"
	"code.byted.org/middleware/hertz/pkg/common/utils"
	"code.byted.org/middleware/hertz_ext/v2/binding"
)

// Ping .
func Ping(ctx context.Context, c *app.RequestContext) {
	c.JSON(200, utils.H{
		"message": "pong",
	})
}

func bind(c *app.RequestContext) *model.Task {
	body, _ := c.Body()
	var task model.Task
	_ = json.Unmarshal(body, &task)
	return &task
}

func TaskList(ctx context.Context, c *app.RequestContext) {
	req := model.TaskListCondition{}
	err := binding.BindAndValidate(c, &req)
	if err != nil {
		logs.CtxError(ctx, "[TaskList] bind and validate param failed, err: %v", err)
		_ = c.AbortWithError(500, fmt.Errorf("task unmarshal err: %w", err))
		return
	}
	task := model.Task{}
	c.JSON(200, task.TaskList(&req))
}

func Submit(ctx context.Context, c *app.RequestContext) {
	task := bind(c)

	extra := map[string]interface{}{}
	err := json.Unmarshal([]byte(task.Extra), &extra)
	if err != nil {
		_ = c.AbortWithError(500, fmt.Errorf("task extra unmarshal err: %w", err))
		return
	}

	if v, ok := extra["commit_branch"]; ok && v != "" && !strings.HasPrefix(fmt.Sprintf("%s", v), "chore/") {
		_ = c.AbortWithError(500, fmt.Errorf("commit branch must start with chore/"))
		return
	}

	task.Submit()
	c.JSON(200, (&model.Task{}).TaskList(&model.TaskListCondition{}))
}

func Delete(ctx context.Context, c *app.RequestContext) {
	task := bind(c)
	if task.ID != 0 || task.RepoName != "" {
		task.Delete()
	}
	c.JSON(200, (&model.Task{}).TaskList(&model.TaskListCondition{}))
}

func GetDependent(ctx context.Context, c *app.RequestContext) {
	v := codemeta.DependentMgr.Get(c.Query("repo"))
	if v == nil {
		v = []string{}
	}
	c.JSON(200, v)
}
