import {
  ArrowDown,
  ArrowLeft,
  ArrowUp,
  ArrowUpDown,
  BellRing,
  Calendar,
  Check,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CornerUpLeft,
  ChevronsUpDown,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  Columns2,
  Columns3,
  ClipboardCheck,
  Database,
  ExternalLink,
  FileCode,
  FileText,
  GitBranch,
  GitCompare,
  GitMerge,
  Hand,
  Eye,
  Flag,
  Image,
  Info,
  Inbox,
  Layers,
  LayoutGrid,
  List,
  Loader,
  Loader2,
  Menu,
  MessageCircle,
  Pencil,
  Play,
  Plus,
  Package,
  Puzzle,
  Radio,
  RotateCcw,
  RefreshCw,
  Save,
  Search,
  Send,
  Settings,
  Shield,
  ShieldAlert,
  SlidersHorizontal,
  Square,
  Star,
  StickyNote,
  StopCircle,
  Swords,
  Target,
  TestTube,
  TriangleAlert,
  Trash2,
  Upload,
  User,
  Users,
  WandSparkles,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react'

type Props = {
  name: string
  className?: string
  size?: number
}

const ICONS: Record<string, LucideIcon> = {
  grid: LayoutGrid,
  'layout-grid': LayoutGrid,
  menu: Menu,
  inbox: Inbox,
  bolt: Zap,
  zap: Zap,
  users: Users,
  skills: Puzzle,
  puzzle: Puzzle,
  settings: Settings,
  docs: FileText,
  'file-text': FileText,
  plus: Plus,
  package: Package,
  refresh: RefreshCw,
  search: Search,
  filter: SlidersHorizontal,
  'sliders-horizontal': SlidersHorizontal,
  sort: ArrowUpDown,
  'arrow-up-down': ArrowUpDown,
  'arrow-down': ArrowDown,
  'arrow-up': ArrowUp,
  'arrow-up-right': ExternalLink,
  layers: Layers,
  fields: Columns2,
  'columns-2': Columns2,
  board: Columns3,
  'columns-3': Columns3,
  list: List,
  back: ArrowLeft,
  sword: Swords,
  swords: Swords,
  mage: WandSparkles,
  'wand-sparkles': WandSparkles,
  wand: WandSparkles,
  clock: Loader,
  loader: Loader,
  spinner: Loader2,
  check: Check,
  'check-square': CheckSquare,
  'circle-check': CircleCheck,
  x: X,
  play: Play,
  stop: StopCircle,
  user: User,
  branch: GitBranch,
  'git-branch': GitBranch,
  compare: GitCompare,
  'git-compare': GitCompare,
  merge: GitMerge,
  'git-merge': GitMerge,
  alert: TriangleAlert,
  'alert-triangle': TriangleAlert,
  'triangle-alert': TriangleAlert,
  error: CircleAlert,
  'circle-alert': CircleAlert,
  'circle-help': CircleHelp,
  info: Info,
  code: FileCode,
  'file-code': FileCode,
  'file-diff': GitCompare,
  database: Database,
  shield: Shield,
  'shield-alert': ShieldAlert,
  send: Send,
  eye: Eye,
  flag: Flag,
  note: StickyNote,
  'sticky-note': StickyNote,
  rework: RotateCcw,
  'rotate-ccw': RotateCcw,
  'chevrons-up-down': ChevronsUpDown,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'corner-up-left': CornerUpLeft,
  pencil: Pencil,
  copy: ClipboardCheck,
  trash: Trash2,
  'trash-2': Trash2,
  'bell-ring': BellRing,
  'clipboard-check': ClipboardCheck,
  hand: Hand,
  'message-circle': MessageCircle,
  calendar: Calendar,
  'test-tube': TestTube,
  save: Save,
  open: ExternalLink,
  'external-link': ExternalLink,
  upload: Upload,
  image: Image,
  signal: Radio,
  radio: Radio,
  target: Target,
  star: Star,
  default: Star,
}

export default function Icon({ name, className, size }: Props) {
  const Glyph = ICONS[name] || Square
  return <Glyph aria-hidden="true" className={'icon ' + (className || '')} size={size} strokeWidth={2} />
}
