// Code generated by hertztool. DO NOT EDIT.

package main

import (
	"code.byted.org/middleware/hertz/pkg/app/server"
	router "code.byted.org/webcast/endpoint_hertz_simple/biz/router"
)

// register registers all routers.
func register(r *server.Hertz) {

	router.GeneratedRegister(r)

	customizedRegister(r)

}
