// Code generated by hertztool

package main

import (
	"code.byted.org/middleware/hertz/pkg/app/server"
	handler "code.byted.org/webcast/endpoint_hertz_simple/biz/handler"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)
	// your code ...
	r.GET("/toclean/m1", handler.ToClean1)
	r.GET("/toclean/m2", handler.ToClean2)
}
