// Code generated by COMMENTS_BUILD_TOOLS 2.0.77. DO NOT EDIT.
package model

import (
	"time"

	"code.byted.org/appmonitor/orm_tools/kms_fields"
)

func (StarAuthorInfo) TableName() string {
	return "star_author_info"
}

func NewStarAuthorInfo() *StarAuthorInfo {
	return &StarAuthorInfo{}
}

type StarAuthorInfo struct {
	InWihteList         int8      `gorm:"column:in_wihte_list;default:0" json:"in_wihte_list"` // 白名单标识，0表示不在，1表示在
	Status              int8      `gorm:"column:status;default:0" json:"status"`
	AuthorType          int8      `gorm:"column:author_type;default:1" json:"author_type"`                   // 达人类型：1 直签，2 mcn签约
	QualificationStatus int8      `gorm:"column:qualification_status;default:0" json:"qualification_status"` // 抖音侧开通任务的认证状态1-认证通过2-未认证3-认证不通过
	TaskStatus          int8      `gorm:"column:task_status;default:0" json:"task_status"`                   // 任务开通状态，1-未开通2-已开通
	SignStatus          int8      `gorm:"column:sign_status;default:2" json:"sign_status"`                   // 签约状态
	Gender              int8      `gorm:"column:gender;default:0" json:"gender"`                             // 性别
	OnlineStatus        int8      `gorm:"column:online_status;default:1" json:"online_status"`               // 1表示在线, 2表示打烊
	AbandonSignResult   int8      `gorm:"column:abandon_sign_result;default:0" json:"abandon_sign_result"`   // 达人主动解约过程状态，const.AuthorAbandonSignResult
	Grade               int8      `gorm:"column:grade;default:1" json:"grade"`                               // 达人等级
	ECommerceEnable     int8      `gorm:"column:e_commerce_enable;default:0" json:"e_commerce_enable"`       // 是否允许带货标志
	Deleted             int8      `gorm:"column:deleted;default:0" json:"deleted"`                           // 0 表示未删除, 1 表示已删除
	Follower            int       `gorm:"column:follower;default:0" json:"follower"`                         // 粉丝数
	Price               int       `gorm:"column:price;default:0" json:"price"`                               // 达人出价
	ShowPrice           int       `gorm:"column:show_price;default:0" json:"show_price"`
	AvgPlay             int       `gorm:"column:avg_play;default:0" json:"avg_play"`
	IncomePrice         int       `gorm:"column:income_price" json:"income_price"`                   // 达人收益价格
	FinishOrderCnt      int       `gorm:"column:finish_order_cnt;default:0" json:"finish_order_cnt"` // 完成订单数
	LongVideoPrice      int       `gorm:"column:long_video_price;default:0" json:"long_video_price"` // 达人长视频出价
	LowestPrice         int       `gorm:"column:lowest_price;default:0" json:"lowest_price"`
	Rate                float32   `gorm:"column:rate;default:0" json:"rate"`
	CutRate             float32   `gorm:"column:cut_rate;default:0" json:"cut_rate"` // 达人报价抽成比例
	Id                  int64     `gorm:"column:id;primary_key" json:"id"`
	CoreUserId          int64     `gorm:"column:core_user_id;default:0" json:"core_user_id"`
	ShortId             int64     `gorm:"column:short_id;default:0" json:"short_id"`
	ProtocolId          int64     `gorm:"column:protocol_id;default:0" json:"protocol_id"` // 协议ID
	AppealId            int64     `gorm:"column:appeal_id" json:"appeal_id"`               // 抖音认证申诉ID
	CategoryId          int64     `gorm:"column:category_id" json:"category_id"`           // 达人类别id
	SignId              int64     `gorm:"column:sign_id;default:0" json:"sign_id"`         // 签约记录ID
	Score               int64     `gorm:"column:score;default:0" json:"score"`             // 排序评分
	CreateTime          time.Time `gorm:"column:create_time;default:current_time" json:"create_time"`
	ModifyTime          time.Time `gorm:"column:modify_time;default:current_time" json:"modify_time"`
	SignUpdateTime      time.Time `gorm:"column:sign_update_time;default:0000-00-00 00:00:00" json:"sign_update_time"` // 签约更新时间
	UniqueId            string    `gorm:"column:unique_id;default:" json:"unique_id"`
	NickName            string    `gorm:"column:nick_name;default:" json:"nick_name"`   // 昵称
	AvatarUri           string    `gorm:"column:avatar_uri;default:" json:"avatar_uri"` // 头像地址
	IdCardNo            string    `gorm:"column:id_card_no;default:" json:"id_card_no"` // 身份证号
	//IdCardNoEncrypt      kms_fields.KmsMetaString `gorm:"column:id_card_no_encrypt" json:"id_card_no_encrypt"` // 身份证号
	RealName string `gorm:"column:real_name;default:" json:"real_name"`
	//RealNameEncrypt      kms_fields.KmsMetaString `gorm:"column:real_name_encrypt" json:"real_name_encrypt"`           // 认证真名
	Phone         string                   `gorm:"column:phone;default:" json:"phone"`                   // 接单手机号
	PhoneEncrypt  kms_fields.KmsMetaString `gorm:"column:phone_encrypt;default:" json:"phone_encrypt"`   // 接单手机号密文 options:{"type": {"value": "kms_fields.KmsQueryString", "import": "code.byted.org/appmonitor/orm_tools/kms_fields"}}
	Province      string                   `gorm:"column:province;default:null" json:"province"`         // 省份
	City          string                   `gorm:"column:city;default:null" json:"city"`                 // 城市
	Tags          string                   `gorm:"column:tags;default:null" json:"tags"`                 // 达人标签
	WithdrawPhone string                   `gorm:"column:withdraw_phone;default:" json:"withdraw_phone"` // 提现手机号，不可重复
	//WithdrawPhoneEncrypt kms_fields.KmsMetaString `gorm:"column:withdraw_phone_encrypt" json:"withdraw_phone_encrypt"` // options:{"type": {"value": "kms_fields.KmsQueryString", "import": "code.byted.org/appmonitor/orm_tools/kms_fields"}}
	TagContentLevelOne string `gorm:"column:tag_content_level_one;default:" json:"tag_content_level_one"`
	TagContentLevelTwo string `gorm:"column:tag_content_level_two;default:" json:"tag_content_level_two"`
	TagAuthorStyle     string `gorm:"column:tag_author_style;default:" json:"tag_author_style"`
	OpenedTaskCategory string `gorm:"column:opened_task_category;default:" json:"opened_task_category"` // 已开通任务
	FrozenTaskCategory string `gorm:"column:frozen_task_category;default:" json:"frozen_task_category"` // 已禁用任务
}
