// Code generated by COMMENTS_BUILD_TOOLS 2.0.77. DO NOT EDIT.
package star_author_info

import (
	"database/sql"
	"errors"

	"code.byted.org/ad/star_goauthor/infrastructure/mysql/model"
	"code.byted.org/gopkg/logs"
	"gorm.io/gorm"
)

var GlobalErrDao = struct {
	EmptySliceErr           error
	EmptyParameter          error
	AttrSizeInConsistentErr error
	NothingExecute          error
}{
	errors.New("EmptySliceError"),
	errors.New("EmptyParameter"),
	errors.New("AttrSizeInConsistentErr"),
	errors.New("NothingExecuteErr"),
}

func NewDao(handler *gorm.DB) Dao {
	return &_DaoStruct{
		handler: handler,
	}
}

type _DaoStruct struct {
	handler *gorm.DB
}

func (interstruct *_DaoStruct) BeginWithHandler(handler *gorm.DB) Dao {
	_ret := _DaoStruct(*interstruct)
	_ret.handler = handler
	return &_ret
}
func (interstruct *_DaoStruct) GetHandler() *gorm.DB {
	return interstruct.handler
}
func (interstruct *_DaoStruct) QueryAnyOne() (*model.StarAuthorInfo, error) {
	_result, _retErr := func() (*model.StarAuthorInfo, error) {
		_sqlText := "select * from star_author_info limit 1"
		_db := interstruct.handler
		_sdb := _db.Raw(_sqlText)
		if _sdb.Error != nil {
			logs.Errorf("execute: %s, occur error: %s", _sqlText, _sdb.Error.Error())
			return nil, _sdb.Error
		}
		var _ret = new(model.StarAuthorInfo)
		_sdb = _sdb.Scan(_ret)
		if _sdb.Error != nil {
			if _sdb.Error != gorm.ErrRecordNotFound && _sdb.Error != sql.ErrNoRows {
				logs.Errorf("Scan: %s, occur error: %s", _sqlText, _sdb.Error.Error())
			}
			return nil, _sdb.Error
		}
		if _sdb.RowsAffected <= 0 {
			return nil, gorm.ErrRecordNotFound
		}
		return _ret, nil
	}()
	return _result, _retErr
}
