// Code generated by Kitex v1.18.0. DO NOT EDIT.

package myservice

import (
	client "code.byted.org/kite/kitex/client"
	handler_dir "code.byted.org/webcast/endpoint_kitex_handler_dir/kitex_gen/endpoint/kitex/handler_dir"
	"context"
	"errors"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Hello": kitex.NewMethodInfo(
		helloHandler,
		newMyServiceHelloArgs,
		newMyServiceHelloResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ToClean1": kitex.NewMethodInfo(
		toClean1Handler,
		newMyServiceToClean1Args,
		newMyServiceToClean1Result,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ToClean2": kitex.NewMethodInfo(
		toClean2Handler,
		newMyServiceToClean2Args,
		newMyServiceToClean2Result,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	myServiceServiceInfo                = NewServiceInfo()
	myServiceServiceInfoForClient       = NewServiceInfoForClient()
	myServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return myServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return myServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return myServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "MyService"
	handlerType := (*handler_dir.MyService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "handler_dir",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v1.18.0",
		Extra:           extra,
	}
	return svcInfo
}

func helloHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*handler_dir.MyServiceHelloArgs)
	realResult := result.(*handler_dir.MyServiceHelloResult)
	success, err := handler.(handler_dir.MyService).Hello(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newMyServiceHelloArgs() interface{} {
	return handler_dir.NewMyServiceHelloArgs()
}

func newMyServiceHelloResult() interface{} {
	return handler_dir.NewMyServiceHelloResult()
}

func toClean1Handler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*handler_dir.MyServiceToClean1Args)
	realResult := result.(*handler_dir.MyServiceToClean1Result)
	success, err := handler.(handler_dir.MyService).ToClean1(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMyServiceToClean1Args() interface{} {
	return handler_dir.NewMyServiceToClean1Args()
}

func newMyServiceToClean1Result() interface{} {
	return handler_dir.NewMyServiceToClean1Result()
}

func toClean2Handler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*handler_dir.MyServiceToClean2Args)
	realResult := result.(*handler_dir.MyServiceToClean2Result)
	success, err := handler.(handler_dir.MyService).ToClean2(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMyServiceToClean2Args() interface{} {
	return handler_dir.NewMyServiceToClean2Args()
}

func newMyServiceToClean2Result() interface{} {
	return handler_dir.NewMyServiceToClean2Result()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Hello(ctx context.Context, req *handler_dir.MyReq) (r string, err error) {
	var _args handler_dir.MyServiceHelloArgs
	_args.Req = req
	var _result handler_dir.MyServiceHelloResult
	if err = p.c.Call(ctx, "Hello", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ToClean1(ctx context.Context, req *handler_dir.ToCleanReq) (r *handler_dir.ToCleanResp, err error) {
	var _args handler_dir.MyServiceToClean1Args
	_args.Req = req
	var _result handler_dir.MyServiceToClean1Result
	if err = p.c.Call(ctx, "ToClean1", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ToClean2(ctx context.Context, req *handler_dir.ToCleanReq) (r *handler_dir.ToCleanResp, err error) {
	var _args handler_dir.MyServiceToClean2Args
	_args.Req = req
	var _result handler_dir.MyServiceToClean2Result
	if err = p.c.Call(ctx, "ToClean2", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
