// Code generated by hertztool.

package main

import (
	"code.byted.org/gopkg/env"
	"code.byted.org/middleware/hertz/byted"
	"code.byted.org/middleware/hertz_ext/v2/middlewares/cors"
	bdsso "code.byted.org/ucenter/bdsso_sessionlib"
)

func main() {
	byted.Init()
	r := byted.Default()
	bdsso.MustInit(env.PSM())
	r.Use(bdsso.SessionHertzMiddleware)
	r.Use(cors.Default())
	register(r)
	r.Spin()
}
