// Code generated by hertztool

package main

import (
	"code.byted.org/analyzers/go_cleaner/app/cleaner/api/biz/handler"
	"code.byted.org/middleware/hertz/pkg/app/server"
)

// register routes based on the IDL 'api.${HTTP Method}' annotation.
func register(r *server.Hertz) {
	//INSERT POINT: DO NOT CHANGE NEXT LINE!
	customizeRegister(r)

	r.GET("/ping", handler.Ping)
}
