// Code generated by hertztool
package main

import (
	"context"
	"strings"
	"time"

	"github.com/cloudwego/hertz/pkg/app"

	"code.byted.org/analyzers/go_cleaner/app/cleaner/api/biz/handler"
	"code.byted.org/gopkg/logs"
	"code.byted.org/middleware/hertz/pkg/app/server"
	bdsso "code.byted.org/ucenter/bdsso_sessionlib"
)

// customizeRegister register customize routers.
func customizeRegister(r *server.Hertz) {
	g := r.Group("/api")
	g.Use(func(c context.Context, ctx *app.RequestContext) {
		session, err := bdsso.GetHertzSession(ctx)
		logs.CtxInfo(c, "session: %v, err:%v", session, err)
		if err != nil {
			return
		}
		isLogin, err := session.IsLogin(c)
		logs.CtxInfo(c, "login:%v, err:%v", isLogin, err)
		email, err := session.Email(c)
		logs.CtxInfo(c, "email:%v, err:%v", email, err)
		if email == "" || !strings.HasSuffix(email, "@bytedance.com") {
			ctx.Abort()
		}
	})
	g.GET("/task", handler.TaskList)
	g.POST("/task/submit", handler.Submit)
	g.POST("/task/delete", handler.Delete)

	g.GET("/task/repo/dependent", handler.GetDependent)

	ab := g.Group("ab")
	ab.Use(func(c context.Context, ctx *app.RequestContext) {
		if currentHour := time.Now().Hour(); currentHour > 2 && currentHour < 10 {
			ctx.Abort()
		}
	})
	ab.GET("entry", handler.MultiGetABEntry)
	ab.POST("entry/save", handler.SaveABEntry)
	ab.POST("entry/delete", handler.DeleteABEntry)

	var f app.PathRewriteFunc = func(ctx *app.RequestContext) []byte {
		path := string(ctx.Path())
		if strings.HasPrefix(path, "/static") || strings.HasPrefix(path, "/api") {
			return ctx.Path()
		}
		return app.NewPathSlashesStripper(1)(ctx)
	}

	fs := &app.FS{Root: "./static", IndexNames: []string{"index.html"}, PathRewrite: f}
	r.StaticFS("/", fs)
}
