// Code generated by Kitex v1.18.0. DO NOT EDIT.

package myservice

import (
	byted "code.byted.org/kite/kitex/byted"
	client "code.byted.org/kite/kitex/client"
	callopt "code.byted.org/kite/kitex/client/callopt"
	specify_handler "code.byted.org/webcast/endpoint_kitex_specify_handler/kitex_gen/endpoint/kitex/specify_handler"
	"context"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Hello(ctx context.Context, req *specify_handler.MyReq, callOptions ...callopt.Option) (r string, err error)
	ToClean1(ctx context.Context, req *specify_handler.ToCleanReq, callOptions ...callopt.Option) (r *specify_handler.ToCleanResp, err error)
	ToClean2(ctx context.Context, req *specify_handler.ToCleanReq, callOptions ...callopt.Option) (r *specify_handler.ToCleanResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	config := byted.NewClientConfig()
	config.DestService = destService
	options = append(options, byted.ClientSuiteWithConfig(serviceInfo(), config))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kMyServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kMyServiceClient struct {
	*kClient
}

func (p *kMyServiceClient) Hello(ctx context.Context, req *specify_handler.MyReq, callOptions ...callopt.Option) (r string, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Hello(ctx, req)
}

func (p *kMyServiceClient) ToClean1(ctx context.Context, req *specify_handler.ToCleanReq, callOptions ...callopt.Option) (r *specify_handler.ToCleanResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ToClean1(ctx, req)
}

func (p *kMyServiceClient) ToClean2(ctx context.Context, req *specify_handler.ToCleanReq, callOptions ...callopt.Option) (r *specify_handler.ToCleanResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ToClean2(ctx, req)
}

// NewClientWithBytedConfig creates a client for the service defined in IDL.
func NewClientWithBytedConfig(destService string, config *byted.ClientConfig, opts ...client.Option) (Client, error) {
	if config == nil {
		config = byted.NewClientConfig()
	}
	config.DestService = destService

	var options []client.Option
	options = append(options, client.WithDestService(destService))

	clientServiceInfo := serviceInfo()

	options = append(options, byted.ClientSuiteWithConfig(clientServiceInfo, config))
	options = append(options, opts...)
	kc, err := client.NewClient(clientServiceInfo, options...)
	if err != nil {
		return nil, err
	}
	return &kMyServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClientWithBytedConfig creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClientWithBytedConfig(destService string, config *byted.ClientConfig, opts ...client.Option) Client {
	kc, err := NewClientWithBytedConfig(destService, config, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}
