import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import YAML from 'yaml';
import { runCmd } from '../../util/exec.js';
import { fileExists } from '../../util/fs.js';
import { ensureBinary } from '../auto-install.js';
import { hashRuleSource, type ToolAdapter, type AdapterContext, type PreflightResult, type RawRunOutput } from '../adapter.js';
import type { Violation } from '../../types.js';

interface ActionlintError {
  filepath: string;
  line: number;
  column: number;
  message: string;
  kind: string;
}

export interface WorkflowComplexity {
  file: string;
  jobCount: number;
  stepCount: number;
  matrixCombinations: number;
  unpinnedActions: number;
  shaPinnedActions: number;
  totalActionsUses: number;
}

export function computeWorkflowComplexity(file: string, yaml: string): WorkflowComplexity {
  const doc = (YAML.parse(yaml) ?? {}) as Record<string, unknown>;
  const jobs = (doc.jobs ?? {}) as Record<
    string,
    {
      steps?: Array<{ uses?: string; run?: string }>;
      strategy?: { matrix?: Record<string, unknown[]> };
    }
  >;
  const jobNames = Object.keys(jobs);
  let stepCount = 0;
  let matrixCombinations = 0;
  let unpinned = 0;
  let shaPinned = 0;
  let totalUses = 0;

  for (const name of jobNames) {
    const j = jobs[name];
    for (const s of j.steps ?? []) {
      stepCount++;
      if (s.uses) {
        totalUses++;
        const match = s.uses.match(/^([^@]+)@(.+)$/);
        if (!match) {
          unpinned++;
        } else if (/^[0-9a-f]{40}$/.test(match[2])) {
          shaPinned++;
        }
      }
    }
    const matrix = j.strategy?.matrix;
    if (matrix) {
      const combos = Object.values(matrix)
        .filter((v): v is unknown[] => Array.isArray(v))
        .map((v) => v.length)
        .reduce((a, b) => a * b, 1);
      matrixCombinations += combos;
    }
  }

  return {
    file,
    jobCount: jobNames.length,
    stepCount,
    matrixCombinations,
    unpinnedActions: unpinned,
    shaPinnedActions: shaPinned,
    totalActionsUses: totalUses,
  };
}

const STARTER_YAML = (date: string): string =>
  `# ─── Generated by architecture-review skill on ${date} ───
# Purpose: enable all actionlint checks.
# Review & commit if useful, OR delete this file to discard.
# ────────────────────────────────────────────────────────────────
# (actionlint does not yet require any disable config; this file documents the skill's intent.)
`;

interface Bundle {
  errors: ActionlintError[];
  complexity: WorkflowComplexity[];
}

export const actionlintAdapter: ToolAdapter & {
  normalizeFromParsed(errors: ActionlintError[], complexity: WorkflowComplexity[], ctx: AdapterContext): Violation[];
} = {
  id: 'actionlint',

  detectApplies(profile) {
    return profile.ghaWorkflows.length > 0;
  },

  async preflight(ctx): Promise<PreflightResult> {
    const ensured = await ensureBinary({
      binary: 'actionlint',
      installPlan: [{ via: 'go-install', pkg: 'github.com/rhysd/actionlint/cmd/actionlint@latest' }],
    });
    if (!ensured.ready) return { ready: false, reason: 'install-failed' };

    let generated: string | undefined;
    if (!ctx.profile.detectedConfigs.actionlint) {
      const path = join(ctx.profile.rootPath, '.actionlint.yaml');
      if (!(await fileExists(path))) {
        await writeFile(path, STARTER_YAML(new Date().toISOString().slice(0, 10)));
        generated = '.actionlint.yaml';
      }
    }

    return { ready: true, installedVia: ensured.installedVia, generatedConfigPath: generated };
  },

  async run(ctx): Promise<RawRunOutput> {
    const rawOutputPath = join(ctx.tmpDir, 'actionlint.json');
    const r = await runCmd('actionlint', ['-format', '{{json .}}', ...ctx.profile.ghaWorkflows], {
      cwd: ctx.profile.rootPath,
      timeoutMs: ctx.timeoutMs,
    });

    const complexity: WorkflowComplexity[] = [];
    for (const wf of ctx.profile.ghaWorkflows) {
      try {
        const yaml = await readFile(join(ctx.profile.rootPath, wf), 'utf-8');
        complexity.push(computeWorkflowComplexity(wf, yaml));
      } catch {
        /* ignore */
      }
    }

    let errors: ActionlintError[];
    try {
      errors = JSON.parse(r.stdout || '[]');
    } catch {
      errors = [];
    }

    const bundle: Bundle = { errors, complexity };
    await writeFile(rawOutputPath, JSON.stringify(bundle, null, 2));

    return {
      rawOutputPath,
      exitCode: r.exitCode,
      stdout: JSON.stringify(bundle),
      stderr: r.stderr,
      durationMs: r.durationMs,
    };
  },

  normalize(raw, ctx): Violation[] {
    let bundle: Bundle;
    try {
      bundle = JSON.parse(raw.stdout);
    } catch {
      bundle = { errors: [], complexity: [] };
    }
    return this.normalizeFromParsed(bundle.errors, bundle.complexity, ctx);
  },

  normalizeFromParsed(errors, complexity, ctx): Violation[] {
    void ctx;
    const out: Violation[] = [];

    for (const e of errors) {
      out.push({
        id: hashRuleSource('actionlint', e.kind, e.filepath, `${e.line}:${e.column}`),
        source: 'l1-tool:actionlint',
        category: 'build-deploy',
        ruleId: `actionlint:${e.kind}`,
        ruleSource: 'skill-builtin',
        severity: 'medium',
        locations: [{ file: e.filepath, line: e.line }],
        evidence: { signals: [`kind=${e.kind}`] },
        message: e.message,
      });
    }

    for (const c of complexity) {
      if (c.matrixCombinations > 12) {
        out.push({
          id: hashRuleSource('actionlint', 'matrix-explosion', c.file),
          source: 'l1-tool:actionlint',
          category: 'build-deploy',
          ruleId: 'matrix-explosion',
          ruleSource: 'skill-builtin',
          severity: 'medium',
          locations: [{ file: c.file }],
          evidence: {
            metric: { name: 'matrix-combos', value: c.matrixCombinations, threshold: 12 },
          },
          message: `Workflow ${c.file} has ${c.matrixCombinations} matrix combinations (threshold 12)`,
        });
      }

      if (c.totalActionsUses > 0 && c.shaPinnedActions / c.totalActionsUses < 0.5) {
        out.push({
          id: hashRuleSource('actionlint', 'low-sha-pin-ratio', c.file),
          source: 'l1-tool:actionlint',
          category: 'security-boundary',
          ruleId: 'low-sha-pin-ratio',
          ruleSource: 'skill-builtin',
          severity: 'medium',
          locations: [{ file: c.file }],
          evidence: {
            metric: { name: 'sha-pin-ratio', value: c.shaPinnedActions / c.totalActionsUses, threshold: 0.5 },
          },
          message: `Workflow ${c.file} has only ${c.shaPinnedActions}/${c.totalActionsUses} actions SHA-pinned`,
        });
      }
    }

    return out;
  },
};
