import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { runCmd } from '../../util/exec.js';
import { fileExists } from '../../util/fs.js';
import { ensureBinary } from '../auto-install.js';
import { hashRuleSource, type ToolAdapter, type AdapterContext, type PreflightResult, type RawRunOutput } from '../adapter.js';
import type { Violation } from '../../types.js';

interface ArchGoVerification { package: string; passes: boolean; details: string[] }
interface ArchGoRuleResult { rule: string; passes: boolean; verifications: ArchGoVerification[] }
interface ArchGoReport {
  pass: boolean;
  details?: {
    dependenciesRuleResults?: ArchGoRuleResult[];
    functionsRuleResults?: ArchGoRuleResult[];
    contentsRuleResults?: ArchGoRuleResult[];
    namingRuleResults?: ArchGoRuleResult[];
  };
  compliance?: number;
  coverage?: number;
}

function pkgToFile(pkg: string): string {
  const parts = pkg.split('/');
  return parts.slice(-2).join('/') + '/';
}

// Layering convention is now dynamic — discovered by LLM during L0 pre-scan
// and stored in RepoProfile.layering. The fallback is the classic ByteDance
// web-service convention for backward compatibility.
import type { LayeringConvention } from '../../types.js';
import { FALLBACK_CONVENTION } from '../../l0-prescan/layer-discovery.js';

interface LayerHit { layer: string; matchedTop: string }

function detectLayers(topPackages: string[], layerOrder: string[]): LayerHit[] {
  const hits: LayerHit[] = [];
  for (const layer of layerOrder) {
    const matched = topPackages.find((p) => {
      // accept either bare top-level (`handler`) or biz-prefixed (`biz/handler`)
      const last = p.split('/').slice(-1)[0];
      const second = p.split('/').slice(-2, -1)[0] ?? '';
      return p === layer || last === layer || second === layer;
    });
    if (matched) hits.push({ layer, matchedTop: matched });
  }
  return hits;
}

function generateStarterYaml(topPackages: string[], convention: LayeringConvention): string | undefined {
  const today = new Date().toISOString().slice(0, 10);
  const layerOrder = convention.hasLayering && convention.layers.length >= 2
    ? convention.layers
    : FALLBACK_CONVENTION.layers;
  const lines = [
    `# ─── Generated by architecture-review skill on ${today} ───`,
    `# Purpose: starter arch-go rules inferred from package layout.`,
    `# Layering convention: ${convention.conventionSummary}`,
    `# Review & commit if useful, OR delete this file to discard.`,
    `# ────────────────────────────────────────────────────────────────`,
    ``,
    `version: 1`,
    `threshold:`,
    `  compliance: 80`,
    `  coverage: 100`,
    `dependenciesRules:`,
  ];

  // Path 1 — Layered architecture detected (dynamic or fallback).
  const layers = detectLayers(topPackages, layerOrder);
  if (layers.length >= 2) {
    lines.push(`  # ── Detected layered architecture: ${layers.map((l) => l.layer).join(' → ')} ──`);
    // Each layer must NOT depend on layers above it. We emit pairwise rules
    // (rather than a transitive list) so violations point at the closest jump.
    for (let i = 0; i < layers.length; i++) {
      for (let j = 0; j < i; j++) {
        const lower = layers[i].layer;
        const upper = layers[j].layer;
        // arch-go uses dot-separated Java-style package patterns, NOT slash globs.
        // e.g. "**.service.**" matches any package path containing "/service/".
        lines.push(
          `  - package: "**.${lower}.**"`,
          `    shouldNotDependsOn:`,
          `      internal:`,
          `        - "**.${upper}.**"`,
        );
      }
    }
    // Hard rule: entry layer (first) must not skip to infra layer (last) directly.
    const entryLayer = layers[0];
    const infraLayer = layers[layers.length - 1];
    if (entryLayer && infraLayer && layers.length >= 3) {
      lines.push(
        `  # ── Hard rule: ${entryLayer.layer} must not skip past middle layers into ${infraLayer.layer} ──`,
        `  - package: "**.${entryLayer.layer}.**"`,
        `    shouldNotDependsOn:`,
        `      internal:`,
        `        - "**.${infraLayer.layer}.**"`,
      );
    }
  }

  // Path 2 — domain/infra style (DDD-ish): keep the original behaviour.
  const domain = topPackages.find((p) => p.endsWith('/domain') || p === 'domain');
  const infra = topPackages.find((p) => p.endsWith('/infra') || p === 'infra');
  if (domain && infra) {
    // Convert slash-separated paths to dot-separated for arch-go.
    const domainDot = domain.replace(/\//g, '.');
    const infraDot = infra.replace(/\//g, '.');
    lines.push(
      `  # ── DDD-style: domain must not depend on infra ──`,
      `  - package: "**.${domainDot}.**"`,
      `    shouldNotDependsOn:`,
      `      internal:`,
      `        - "**.${infraDot}.**"`,
    );
  }

  // No fallback no-op rule. If we could not infer anything, the file is left
  // empty so a human can write real rules instead of seeing a vacuous pass.
  if (lines[lines.length - 1] === `dependenciesRules:`) {
    lines.push(
      `  # No layering convention auto-detected. Add real rules here, e.g.:`,
      `  # - package: "**.api.**"`,
      `  #   shouldNotDependsOn:`,
      `  #     internal:`,
      `  #       - "**.internal.**"`,
    );
  }

  return lines.join('\n') + '\n';
}

async function writeGeneratedYaml(ctx: AdapterContext): Promise<string | undefined> {
  const target = join(ctx.profile.rootPath, 'arch-go.yml');
  if (await fileExists(target)) return undefined;
  const topGo = ctx.profile.topLevelPackages.go ?? [];
  const convention = ctx.profile.layering ?? FALLBACK_CONVENTION;
  const content = generateStarterYaml(topGo, convention);
  if (!content) return undefined;
  await writeFile(target, content);
  return 'arch-go.yml';
}

export const archGoAdapter: ToolAdapter & {
  normalizeFromParsed(parsed: ArchGoReport, ctx: AdapterContext): Violation[];
} = {
  id: 'arch-go',

  detectApplies(profile) {
    return profile.hasGoMod;
  },

  async preflight(ctx): Promise<PreflightResult> {
    const ensured = await ensureBinary({
      binary: 'arch-go',
      installPlan: [{ via: 'go-install', pkg: 'github.com/arch-go/arch-go@latest' }],
    });
    if (!ensured.ready) return { ready: false, reason: 'install-failed' };
    const generated = await writeGeneratedYaml(ctx);
    return { ready: true, installedVia: ensured.installedVia, generatedConfigPath: generated };
  },

  async run(ctx): Promise<RawRunOutput> {
    const rawOutputPath = join(ctx.tmpDir, 'arch-go.json');
    const reportPath = join(ctx.profile.rootPath, '.arch-go', 'report.json');
    // arch-go v1.7.x has no `check` subcommand; invoke bare binary. Flags
    // must precede args (which are none for whole-repo scan). --json writes
    // to .arch-go/report.json, not to stdout.
    const r = await runCmd('arch-go', ['--json'], { cwd: ctx.profile.rootPath, timeoutMs: ctx.timeoutMs });
    let content = r.stdout;
    if ((!content.trim()) && await fileExists(reportPath)) {
      content = await readFile(reportPath, 'utf-8');
    }
    // Detect arch-go crashes (e.g. nil Regexp from malformed patterns in YAML).
    // arch-go writes its panic stack to stdout, so check both channels. If
    // the binary panicked we must NOT silently report zero violations — that
    // is exactly the failure mode that historically produced false "100/100"
    // reports.
    const combined = (r.stdout || '') + '\n' + (r.stderr || '');
    const crashed = /panic:|SIGSEGV|segmentation violation|runtime error: invalid memory address/i.test(combined);
    if (crashed) {
      const tail = combined.split('\n').filter((l) => l.trim()).slice(-3).join(' | ');
      throw new Error(`arch-go crashed: ${tail.slice(0, 240)}`);
    }
    // If arch-go produced no output at all (neither stdout nor report.json)
    // but also did not crash, it still did not do its job — surface as a
    // failure rather than silent success.
    if (!content.trim()) {
      throw new Error(`arch-go produced no output (exit=${r.exitCode}, stderr=${(r.stderr || '').slice(0, 120)})`);
    }
    await writeFile(rawOutputPath, content);
    return { rawOutputPath, exitCode: r.exitCode, stdout: content, stderr: r.stderr, durationMs: r.durationMs };
  },

  normalize(raw, ctx): Violation[] {
    let parsed: ArchGoReport;
    try { parsed = JSON.parse(raw.stdout || '{}'); } catch { parsed = { pass: true }; }
    return this.normalizeFromParsed(parsed, ctx);
  },

  normalizeFromParsed(parsed, ctx): Violation[] {
    const out: Violation[] = [];
    const ruleSource: Violation['ruleSource'] = ctx.profile.detectedConfigs.archGo ? 'repo-config' : 'skill-generated';

    const sections: Array<{ kind: Violation['category']; family: string; rules?: ArchGoRuleResult[] }> = [
      { kind: 'layering', family: 'dependencies', rules: parsed.details?.dependenciesRuleResults },
      { kind: 'structure', family: 'functions', rules: parsed.details?.functionsRuleResults },
      { kind: 'structure', family: 'contents', rules: parsed.details?.contentsRuleResults },
      { kind: 'structure', family: 'naming', rules: parsed.details?.namingRuleResults },
    ];

    for (const sec of sections) {
      for (const rule of sec.rules ?? []) {
        if (rule.passes) continue;
        for (const v of rule.verifications) {
          if (v.passes) continue;
          const fileHint = pkgToFile(v.package);
          const detail = v.details?.[0] ?? 'violation';
          out.push({
            id: hashRuleSource('arch-go', `${sec.family}:${rule.rule}`, fileHint, v.package),
            source: 'l1-tool:arch-go',
            category: sec.kind,
            ruleId: `arch-go:${sec.family}:${rule.rule.replace(/\s+/g, '-')}`,
            ruleSource,
            severity: 'high',
            locations: [{ file: fileHint, module: v.package }],
            evidence: { signals: [`rule=${rule.rule}`, `detail=${detail}`] },
            message: `${rule.rule} — ${v.package}: ${detail}`,
          });
        }
      }
    }

    return out;
  },
};
