import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { runCmd } from '../../util/exec.js';
import { fileExists } from '../../util/fs.js';
import { ensureBinary } from '../auto-install.js';
import { hashRuleSource, type ToolAdapter, type AdapterContext, type PreflightResult, type RawRunOutput, type InstallVia } from '../adapter.js';
import type { Violation } from '../../types.js';

interface HadolintDiag {
  file: string;
  line: number;
  column: number;
  level: 'info' | 'warning' | 'error' | 'style';
  code: string;
  message: string;
}

const STARTER_YAML = (date: string): string => `# ─── Generated by architecture-review skill on ${date} ───
# Purpose: enable strict-but-hidden rules (DL3057 missing HEALTHCHECK).
# Review & commit if useful, OR delete this file to discard.
# ────────────────────────────────────────────────────────────────
failure-threshold: warning
override:
  warning:
    - DL3057
`;

function severityFromLevel(level: HadolintDiag['level']): Violation['severity'] {
  if (level === 'error') return 'high';
  if (level === 'warning') return 'medium';
  return 'low';
}

export const hadolintAdapter: ToolAdapter & {
  normalizeFromParsed(parsed: HadolintDiag[], ctx: AdapterContext): Violation[];
} = {
  id: 'hadolint',

  detectApplies(profile) {
    return profile.dockerfiles.length > 0;
  },

  async preflight(ctx): Promise<PreflightResult> {
    const dockerCheck = await runCmd('docker', ['--version'], { timeoutMs: 5_000 });
    let installedVia: InstallVia | undefined;
    if (dockerCheck.status === 'ok') {
      installedVia = 'docker';
    } else {
      const ensured = await ensureBinary({
        binary: 'hadolint',
        installPlan: [
          {
            via: 'binary',
            pkg: 'hadolint',
            args: [
              'sh',
              '-c',
              'curl -fsSL https://github.com/hadolint/hadolint/releases/latest/download/hadolint-$(uname -s)-$(uname -m) -o /usr/local/bin/hadolint && chmod +x /usr/local/bin/hadolint',
            ],
          },
        ],
      });
      if (!ensured.ready) return { ready: false, reason: 'install-failed' };
      installedVia = ensured.installedVia === 'pre-existing' ? 'pre-existing' : 'binary';
    }
    let generated: string | undefined;
    if (!ctx.profile.detectedConfigs.hadolint) {
      const path = join(ctx.profile.rootPath, '.hadolint.yaml');
      if (!(await fileExists(path))) {
        await writeFile(path, STARTER_YAML(new Date().toISOString().slice(0, 10)));
        generated = '.hadolint.yaml';
      }
    }
    return { ready: true, installedVia, generatedConfigPath: generated };
  },

  async run(ctx): Promise<RawRunOutput> {
    const rawOutputPath = join(ctx.tmpDir, 'hadolint.json');
    const args = ['--format', 'json', ...ctx.profile.dockerfiles];
    const docker = await runCmd('docker', ['--version'], { timeoutMs: 5_000 });
    let r;
    if (docker.status === 'ok') {
      r = await runCmd(
        'docker',
        [
          'run',
          '--rm',
          '-i',
          '-v',
          `${ctx.profile.rootPath}:/work`,
          '-w',
          '/work',
          'hadolint/hadolint',
          'hadolint',
          ...args,
        ],
        { timeoutMs: ctx.timeoutMs },
      );
    } else {
      r = await runCmd('hadolint', args, { cwd: ctx.profile.rootPath, timeoutMs: ctx.timeoutMs });
    }
    await writeFile(rawOutputPath, r.stdout || '[]');
    return { rawOutputPath, exitCode: r.exitCode, stdout: r.stdout, stderr: r.stderr, durationMs: r.durationMs };
  },

  normalize(raw, ctx): Violation[] {
    let parsed: HadolintDiag[];
    try {
      parsed = JSON.parse(raw.stdout || '[]');
    } catch {
      parsed = [];
    }
    return this.normalizeFromParsed(parsed, ctx);
  },

  normalizeFromParsed(parsed, ctx): Violation[] {
    void ctx;
    return parsed.map((d) => ({
      id: hashRuleSource('hadolint', d.code, d.file, `${d.line}:${d.column}`),
      source: 'l1-tool:hadolint',
      category: 'build-deploy' as const,
      ruleId: d.code,
      ruleSource: 'skill-builtin' as const,
      severity: severityFromLevel(d.level),
      locations: [{ file: d.file, line: d.line }],
      evidence: { signals: [`hadolint-level=${d.level}`, `message=${d.message}`] },
      message: `${d.code} [${d.level}] ${d.message}`,
    }));
  },
};
