import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { runCmd } from '../../util/exec.js';
import { fileExists } from '../../util/fs.js';
import { ensureBinary } from '../auto-install.js';
import { hashRuleSource, type ToolAdapter, type AdapterContext, type PreflightResult, type RawRunOutput } from '../adapter.js';
import type { Violation } from '../../types.js';

interface ILContract {
  name: string;
  kind: 'Forbidden' | 'Layers' | 'Independence';
  broken: boolean;
  violations?: Array<{ importer: string; imported: string; line_number?: number; line_contents?: string }>;
}
interface ILReport {
  contracts: ILContract[];
}

function importerToFile(importer: string): string {
  return importer.replace(/\./g, '/') + '.py';
}

function generateStarterConfig(topPackages: string[]): string {
  const root = topPackages.find((p) => !p.includes('.'));
  if (!root) return '';
  const domain = topPackages.find((p) => p === `${root}.domain`);
  const infra = topPackages.find((p) => p === `${root}.infra`);
  const sections: string[] = [];
  sections.push(`# ─── Generated by architecture-review skill on ${new Date().toISOString().slice(0, 10)} ───`);
  sections.push(`# Purpose: starter import-linter contracts inferred from directory structure.`);
  sections.push(`# Review & commit if useful, OR delete this section to discard.`);
  sections.push(`# ────────────────────────────────────────────────────────────────`);
  sections.push('');
  sections.push('[importlinter]');
  sections.push(`root_packages =\n    ${root}`);
  sections.push('');
  if (domain && infra) {
    sections.push('[importlinter:contract:domain-not-infra]');
    sections.push('name = domain must not import infra');
    sections.push('type = forbidden');
    sections.push(`source_modules =\n    ${domain}`);
    sections.push(`forbidden_modules =\n    ${infra}`);
    sections.push('');
  }
  sections.push('[importlinter:contract:no-circular]');
  sections.push('name = no circular dependencies inside root package');
  sections.push('type = independence');
  sections.push(`modules =\n    ${root}`);
  sections.push('');
  return sections.join('\n');
}

async function writeGeneratedConfig(ctx: AdapterContext): Promise<string | undefined> {
  const existing = ctx.profile.detectedConfigs.importLinter;
  if (existing) return undefined;
  const topPy = ctx.profile.topLevelPackages.python ?? [];
  const content = generateStarterConfig(topPy);
  if (!content) return undefined;
  const pyproject = join(ctx.profile.rootPath, 'pyproject.toml');
  if (await fileExists(pyproject)) {
    const current = await readFile(pyproject, 'utf-8');
    await writeFile(pyproject, current.trimEnd() + '\n\n' + content);
    return 'pyproject.toml';
  }
  const ini = join(ctx.profile.rootPath, '.importlinter');
  await writeFile(ini, content);
  return '.importlinter';
}

function parseTextReport(stdout: string): ILReport {
  const contracts: ILContract[] = [];
  let current: ILContract | null = null;
  const lines = stdout.split('\n');
  for (const line of lines) {
    const brokenMatch = line.match(/^[-*\s]*(.+?)\s+BROKEN$/);
    const keptMatch = line.match(/^[-*\s]*(.+?)\s+KEPT$/);
    if (brokenMatch) {
      current = { name: brokenMatch[1].trim(), kind: 'Forbidden', broken: true, violations: [] };
      contracts.push(current);
      continue;
    }
    if (keptMatch) {
      current = null;
      continue;
    }
    if (current) {
      const imp = line.match(/^\s+(\S+)\s*->\s*(\S+)(?:\s*\(l\.(\d+)\))?/);
      if (imp) {
        current.violations!.push({
          importer: imp[1],
          imported: imp[2],
          line_number: imp[3] ? parseInt(imp[3], 10) : undefined,
        });
      }
    }
  }
  return { contracts };
}

export const importLinterAdapter: ToolAdapter & {
  normalizeFromParsed(parsed: ILReport, ctx: AdapterContext): Violation[];
} = {
  id: 'import-linter',

  detectApplies(profile) {
    return profile.hasPyProject || profile.hasSetupCfg;
  },

  async preflight(ctx): Promise<PreflightResult> {
    const ensured = await ensureBinary({
      binary: 'lint-imports',
      installPlan: [{ via: 'pipx', pkg: 'import-linter' }],
    });
    if (!ensured.ready) return { ready: false, reason: 'install-failed', installMessage: 'pipx install import-linter failed' };
    const generated = await writeGeneratedConfig(ctx);
    return { ready: true, installedVia: ensured.installedVia, generatedConfigPath: generated };
  },

  async run(ctx): Promise<RawRunOutput> {
    const rawOutputPath = join(ctx.tmpDir, 'import-linter.json');
    const r = await runCmd('lint-imports', ['--show-timings', '--no-cache'], {
      cwd: ctx.profile.rootPath,
      timeoutMs: ctx.timeoutMs,
    });
    await writeFile(rawOutputPath, JSON.stringify({ stdout: r.stdout, stderr: r.stderr, exitCode: r.exitCode }, null, 2));
    return { rawOutputPath, exitCode: r.exitCode, stdout: r.stdout, stderr: r.stderr, durationMs: r.durationMs };
  },

  normalize(raw, ctx): Violation[] {
    const parsed = parseTextReport(raw.stdout);
    return this.normalizeFromParsed(parsed, ctx);
  },

  normalizeFromParsed(parsed, ctx): Violation[] {
    const out: Violation[] = [];
    for (const c of parsed.contracts) {
      if (!c.broken || !c.violations) continue;
      for (const v of c.violations) {
        const file = importerToFile(v.importer);
        const category: Violation['category'] = c.kind === 'Forbidden' || c.kind === 'Layers' ? 'layering' : 'dependency';
        const ruleId = `${c.kind.toLowerCase()}:${c.name.replace(/\s+/g, '-')}`;
        const ruleSource: Violation['ruleSource'] = ctx.profile.detectedConfigs.importLinter ? 'repo-config' : 'skill-generated';
        out.push({
          id: hashRuleSource('import-linter', ruleId, file, v.imported),
          source: 'l1-tool:import-linter',
          category,
          ruleId,
          ruleSource,
          severity: 'high',
          locations: [{ file, line: v.line_number, symbol: v.importer }],
          evidence: {
            signals: [
              `imported=${v.imported}`,
              `contract=${c.name}`,
              ...(v.line_contents ? [`code=${v.line_contents}`] : []),
            ],
          },
          message: `${c.name}: ${v.importer} imports ${v.imported}`,
        });
      }
    }
    return out;
  },
};
