// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameStarPlatformPermission = "star_platform_permission"

// StarPlatformPermission mapped from table <star_platform_permission>
type StarPlatformPermission struct {
	ID                  int64     `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`                                                                          // 自增id
	DomainType          int32     `gorm:"column:domain_type;type:tinyint;not null;uniqueIndex:uniq_domain_operation,priority:1" json:"domain_type"`                                     // 状态：0：未知；1：模块；2：接口等等
	DomainBizIdentifier string    `gorm:"column:domain_biz_identifier;type:varchar(20);not null;uniqueIndex:uniq_domain_operation,priority:2;default:' '" json:"domain_biz_identifier"` // 业务方唯一标识
	Operation           int32     `gorm:"column:operation;type:tinyint;not null;uniqueIndex:uniq_domain_operation,priority:3" json:"operation"`                                         // 操作：0：未知；1：读；2：写；等等
	ModifyTime          time.Time `gorm:"column:modify_time;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"modify_time"`                                                      // 更新时间
	CreatedTime         time.Time `gorm:"column:created_time;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"created_time"`                                                    // 创建时间
	Deleted             int32     `gorm:"column:deleted;type:tinyint;not null" json:"deleted"`                                                                                          // 是否删除：0：否 ；1：是
}

// TableName StarPlatformPermission's table name
func (*StarPlatformPermission) TableName() string {
	return TableNameStarPlatformPermission
}
